window.REPLICATOR_VASES = [
  {
    id: "argent",
    title: "Vase Argent",
    shortDescription: "Un plateau froid et mineral, pense comme une surface de reflet au centre du parcours.",
    positionOnMap: { x: 31, y: 80 },
    tone: "silver",
    gcodeHook: null,
    slides: [
      { title: "Face 1", image: "vase/vase_argent_002.png" },
      { title: "Face 2" },
      { title: "Face 3" },
      { title: "Face 4" },
    ],
  },
  {
    id: "or",
    title: "Vase Or",
    shortDescription: "Un repere solaire dans la chapelle, entre objet rituel et signal lumineux.",
    positionOnMap: { x: 50, y: 84 },
    tone: "gold",
    gcodeHook: null,
    slides: [
      { title: "Face 1", image: "vase/vase_or_004.png" },
      { title: "Face 2" },
      { title: "Face 3" },
      { title: "Face 4" },
    ],
  },
  {
    id: "bronze",
    title: "Vase Bronze",
    shortDescription: "Une presence dense et patinee, proche d'un fragment archeologique augmente.",
    positionOnMap: { x: 69, y: 80 },
    tone: "bronze",
    gcodeHook: null,
    slides: [
      { title: "Face 1", image: "vase/vase_bronze_005.png" },
      { title: "Face 2" },
      { title: "Face 3" },
      { title: "Face 4" },
    ],
  },
  {
    id: "maquette",
    title: "Vase Maquette",
    shortDescription: "Une etude en miniature, entre plan, inclusion et trace de fabrication.",
    positionOnMap: { x: 34, y: 48 },
    tone: "blueprint",
    gcodeHook: null,
    slides: [
      { title: "Visuel face vue interieur", image: "vase/vase_maquette_007.png" },
      { title: "Visuel face inclusion element or et avion" },
      { title: "Visuel face inclusion elements or" },
      { title: "Visuel face de dessous" },
    ],
  },
  {
    id: "boulouris",
    title: "Vase Boulouris",
    shortDescription: "Une piece florale et marine, composee comme un souvenir de paysage.",
    positionOnMap: { x: 66, y: 48 },
    tone: "floral",
    gcodeHook: null,
    slides: [
      { title: "Face du dessous encolure", image: "vase/vase_boulouris_001.png" },
      { title: "Face du dessous" },
      { title: "Face decor floral" },
    ],
  },
  {
    id: "mns-v1",
    title: "Vase MNS V1",
    shortDescription: "Un vase narratif, fait de gestes sportifs, d'indices et d'images fragmentees.",
    positionOnMap: { x: 39, y: 33 },
    tone: "mnsOne",
    gcodeHook: null,
    slides: [
      { title: "Visuel faces crime", image: "vase/vase_MNS_v1_008.png" },
      { title: "Visuel face paume" },
      { title: "Visuel face equitation" },
      { title: "Visuel face plongeon" },
    ],
  },
  {
    id: "mns-v2",
    title: "Vase MNS V2",
    shortDescription: "Une variation plus claire, traversee par des jaunes sourds et des decalages de surface.",
    positionOnMap: { x: 61, y: 33 },
    tone: "mnsTwo",
    gcodeHook: null,
    slides: [
      { title: "Visuel face jaune", image: "vase/vase_MNS_v2_006.png" },
      { title: "Visuel face moins jaune" },
    ],
  },
  {
    id: "poeme",
    title: "Vase Poeme",
    shortDescription: "Le sommet du dispositif, un vase blanc ou l'ecriture devient volume.",
    positionOnMap: { x: 50, y: 27 },
    tone: "poem",
    gcodeHook: null,
    slides: [
      { title: "Visuel face vase blanc", image: "vase/vase_poeme_003.png" },
      { title: "Visuel face poeme" },
    ],
  },
];

window.REPLICATOR_CONSOLE_ORDER = [
  "boulouris",
  "argent",
  "or",
  "bronze",
  "poeme",
  "mns-v2",
  "mns-v1",
  "maquette",
];
