window.REPLICATOR_VASES = [
  {
    id: "maquette",
    order: "01",
    title: "Vase Maquette",
    mapLabel: "Maquette",
    chapter: "Recherche couleur et assemblage",
    shortDescription: "Maquette d'essai: corps bleu, decor or, sillons dans la matiere et assemblage imprime en une seule fois.",
    tone: "maquette",
    physicalState: "Rotation respirante",
    detailAction: "Premier clic: le vase pulse puis tourne avec acceleration progressive et ralentissement. Deuxieme clic: rotation stable, plus lente, pendant la lecture du diaporama.",
    hardware: "Moteur pas a pas X",
    hotspot: { pxX: 1690, pxY: 575 },
    sketchImage: "main/png/maquette-croquis.png",
    gcodeHook: null,
    slides: [
      {
        title: "Maquette 01",
        image: "diapo/vase-maquette/vase_maquette_01.jpg",
        caption: "Le prototype met en relation marqueterie, culture maker et impression 3D.",
      },
      {
        title: "Maquette 02",
        image: "diapo/vase-maquette/vase_maquette_02.jpg",
        caption: "Les motifs sont traites comme des pieces assemblees dans la matiere.",
      },
      {
        title: "Maquette 03",
        image: "diapo/vase-maquette/vase_maquette_03.jpg",
        caption: "Le decor n'est pas seulement pose: il entre dans l'epaisseur du vase.",
      },
      {
        title: "Maquette 04",
        image: "diapo/vase-maquette/vase_maquette_04.jpg",
        caption: "Avions, fleurs et sports apparaissent comme une archive imprimee.",
      },
      {
        title: "Maquette 05",
        image: "diapo/vase-maquette/vase_maquette_05.jpg",
        caption: "Chaque vue accompagne une rotation complete plus calme dans l'espace reel.",
      },
      {
        title: "Maquette 06",
        image: "diapo/vase-maquette/vase_maquette_06.jpg",
        caption: "La piece garde l'esprit du test: visible, technique, encore proche de l'atelier.",
      },
      {
        title: "Maquette 07",
        image: "diapo/vase-maquette/vase_maquette_07.jpg",
        caption: "La maquette devient une preuve de methode autant qu'un objet fini.",
      },
    ],
  },
  {
    id: "mns-creps",
    order: "02",
    title: "Vases Musee National du Sport et CREPS",
    mapLabel: "MNS / CREPS",
    chapter: "Serie signee, flamme olympique",
    shortDescription: "Deux vases issus du projet original de 2023 pour l'accueil de la flamme olympique dans les CREPS de France.",
    tone: "mns",
    physicalState: "Double rotation synchronisee",
    detailAction: "Premier clic: les deux vases s'animent ensemble. Dans le diaporama, chaque page declenche un tour complet; a la fin, une signature s'arrete pendant que le double tourne encore.",
    hardware: "Deux moteurs pas a pas Z couples",
    hotspot: { pxX: 1200, pxY: 555 },
    sketchImage: "main/png/mns-creps-croquis.png",
    gcodeHook: null,
    slides: [
      {
        title: "Shooting 01",
        image: "diapo/vase-mns-creps/vase-mns-creps_01.JPG",
        caption: "La serie existe comme edition: trente pieces signees et numerotees.",
      },
      {
        title: "Shooting 02",
        image: "diapo/vase-mns-creps/vase-mns-creps_02.JPG",
        caption: "L'artiste pose avec la serie, entre archive sportive et objet de ceremonie.",
      },
      {
        title: "Shooting 03",
        image: "diapo/vase-mns-creps/vase-mns-creps_03.JPG",
        caption: "Les rotations synchronisees donnent une lecture differente a chaque vase.",
      },
      {
        title: "Shooting 04",
        image: "diapo/vase-mns-creps/vase-mns-creps_04.jpg",
        caption: "Un vase effectue un tour, l'autre repond par une pirouette.",
      },
      {
        title: "Shooting 05",
        image: "diapo/vase-mns-creps/vase-mns-creps_05.JPG",
        caption: "Le mouvement met en valeur la notion de revers, de numero et de signature.",
      },
      {
        title: "Shooting 06",
        image: "diapo/vase-mns-creps/vase-mns-creps_06.JPG",
        caption: "L'objet sportif devient un objet de transmission.",
      },
      {
        title: "Shooting 07",
        image: "diapo/vase-mns-creps/vase-mns-creps_07.JPG",
        caption: "Le rythme reste commun, mais les axes divergent.",
      },
      {
        title: "Shooting 08",
        image: "diapo/vase-mns-creps/vase-mns-creps_08.JPG",
        caption: "Chaque changement de page relance une petite choregraphie.",
      },
      {
        title: "Shooting 09",
        image: "diapo/vase-mns-creps/vase-mns-creps_09.JPG",
        caption: "La serie se regarde autant comme collection que comme mouvement.",
      },
      {
        title: "Signature",
        image: "diapo/vase-mns-creps/vase-mns-creps_10.JPG",
        caption: "La signature devient le point d'arret, pendant que l'autre vase continue de tourner.",
      },
    ],
  },
  {
    id: "asa",
    order: "03",
    title: "Vase ASA Blanc UV",
    mapLabel: "ASA",
    chapter: "Resistance, sable, vitrine",
    shortDescription: "Version blanche resistante aux rayons UV, presentee dans une vitrine avec sable et flux d'air module.",
    tone: "asa",
    physicalState: "Ventilateur puis agitation variable",
    detailAction: "Premier clic: le ventilateur met les grains de sable en mouvement. Deuxieme clic: le vase alterne gauche et droite avec des vitesses variables, comme s'il evitait les grains.",
    hardware: "Moteur pas a pas Y et ventilateur n.1",
    hotspot: { pxX: 792, pxY: 255},
    sketchImage: "main/png/asa-croquis.png",
    gcodeHook: null,
    slides: [
      {
        title: "Video ASA",
        video: "diapo/vase-asa/vase-asa.mp4",
        caption: "La sequence montre la resistance technique et le comportement de la matiere.",
      },
      {
        title: "Signature",
        video: "diapo/vase-asa/vase-asa-singature.mp4",
        caption: "Le vase devient un objet technique autant qu'un objet signe.",
      },
    ],
  },
  {
    id: "podium",
    order: "04",
    title: "Vases Podium",
    mapLabel: "Podium",
    chapter: "Trois vases, buee et chance",
    shortDescription: "Trois vases en vitrine: une serie olympique pensee comme un dispositif de chance et d'apparition.",
    tone: "podium",
    physicalState: "Buee, chauffage, ventilation",
    detailAction: "Premier clic: le groupe pulse et un voile apparait. Deuxieme clic et parcours du diaporama: le plateau refroidit, le ventilateur expulse l'humidite, la buee disparait progressivement.",
    hardware: "Plateau chauffant, thermistance, ventilateur n.2",
    hotspot: { pxX: 927, pxY: 475 },
    sketchImage: "main/png/podium-croquis.png",
    gcodeHook: null,
    slides: [
      {
        title: "Video podium 01",
        video: "diapo/vase-podium/ektar-vase-podium-2.mp4",
        caption: "Les vases sont lies aux Jeux Olympiques, a la performance et aux gestes porte-bonheur.",
      },
      {
        title: "Video podium 02",
        video: "diapo/vase-podium/teaser-vase-podium-1.mp4",
        caption: "La vitrine devient un petit theatre: chauffage, buee, ventilation et apparition progressive.",
      },
    ],
  },
  {
    id: "poeme",
    order: "05",
    title: "Vase Poeme",
    mapLabel: "Poeme",
    chapter: "Alcove, timidite, face arriere",
    shortDescription: "Place dans une alcove, le vase se tourne lentement pour reveler le poeme inscrit sur sa face arriere.",
    tone: "poeme",
    physicalState: "Rotation lente et retenue",
    detailAction: "Premier clic: le vase se tourne presque timidement. Deuxieme clic: la lecture se poursuit avec une transcription et des vues de face et de revers.",
    hardware: "Moteur pas a pas E, corps chauffant et thermistance",
    hotspot: { pxX: 260, pxY: 282 },
    sketchImage: "main/png/poene-croquiss.png",
    gcodeHook: null,
    slides: [
      {
        title: "Face",
        image: "diapo/vase-poeme/vase-poeme-01.JPG",
        caption: "La face silencieuse prepare la revelation du texte.",
      },
      {
        title: "Profil",
        image: "diapo/vase-poeme/vase-poeme-02.JPG",
        caption: "Le mouvement reste lent pour ne pas brusquer la lecture.",
      },
      {
        title: "Revers",
        image: "diapo/vase-poeme/vase-poeme-03.jpg",
        caption: "Le poeme apparait comme une face cachee.",
      },
      {
        title: "Lecture",
        image: "diapo/vase-poeme/vase-poeme-04.JPG",
        caption: "La tablette rend lisible ce que le vase revele physiquement.",
      },
    ],
  },
];

window.REPLICATOR_CONSOLE_ORDER = ["maquette", "mns-creps", "asa", "podium", "poeme"];

window.REPLICATOR_CHOREOGRAPHIES = [
  {
    id: "global-1",
    label: "Choregraphie 01",
    description: "Tous les vases tournent a la meme vitesse. Les effets montent progressivement puis s'eteignent d'un seul coup.",
  },
  {
    id: "global-2",
    label: "Choregraphie 02",
    description: "Tous les vases accelerent progressivement tandis que les effets deviennent inactifs.",
  },
  {
    id: "atelier",
    label: "Atelier prompt",
    description: "Editeur de choregraphie pour generer des G-codes a partir d'un scenario ecrit, accessible en atelier des 12 ans.",
  },
];
