window.REPLICATOR_VASES = [
  {
    id: "maquette",
    order: "01",
    title: "Vase Maquette",
    mapLabel: "Maquette",
    chapter: "Recherche couleur et assemblage",
    shortDescription: "Maquette d'essai: corps bleu, decor or, sillons dans la matiere et assemblage imprime en une seule fois.",
    tone: "maquette",
    physicalState: "Rotation respirante",
    detailAction: "Premier clic: le vase pulse puis tourne avec acceleration progressive et ralentissement. Deuxieme clic: rotation stable, plus lente, pendant la lecture du diaporama.",
    hardware: "Moteur pas a pas X",
    hotspot: { pxX: 1690, pxY: 610 },
    sketchImage: "main/png/maquette-croquis.png",
    gcodeHook: { name: "Maquette respiration mecanique", endpoint: "/api/choreo/run/maquette_respiration" },
    slides: [
      {
        title: "Maquette 01",
        image: "diapo/vase-maquette/vase_maquette_01.jpg",
        caption: "Le prototype met en relation marqueterie, culture maker et impression 3D.",
        sceneGcodeHook: { name: "Maquette rotation lente stable", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
      {
        title: "Maquette 02",
        image: "diapo/vase-maquette/vase_maquette_02.jpg",
        caption: "Les motifs sont traites comme des pieces assemblees dans la matiere.",
        sceneGcodeHook: { name: "Maquette rotation lente motifs", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
      {
        title: "Maquette 03",
        image: "diapo/vase-maquette/vase_maquette_03.jpg",
        caption: "Le decor n'est pas seulement pose: il entre dans l'epaisseur du vase.",
        sceneGcodeHook: { name: "Maquette rotation lente detail", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
      {
        title: "Maquette 04",
        image: "diapo/vase-maquette/vase_maquette_04.jpg",
        caption: "Avions, fleurs et sports apparaissent comme une archive imprimee.",
        sceneGcodeHook: { name: "Maquette rotation lente archive", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
      {
        title: "Maquette 05",
        image: "diapo/vase-maquette/vase_maquette_05.jpg",
        caption: "Chaque vue accompagne une rotation complete plus calme dans l'espace reel.",
        sceneGcodeHook: { name: "Maquette rotation lente tour complet", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
      {
        title: "Maquette 06",
        image: "diapo/vase-maquette/vase_maquette_06.jpg",
        caption: "La piece garde l'esprit du test: visible, technique, encore proche de l'atelier.",
        sceneGcodeHook: { name: "Maquette rotation lente atelier", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
      {
        title: "Maquette 07",
        image: "diapo/vase-maquette/vase_maquette_07.jpg",
        caption: "La maquette devient une preuve de methode autant qu'un objet fini.",
        sceneGcodeHook: { name: "Maquette rotation lente finale", endpoint: "/api/choreo/run/maquette_rotation_lente" },
      },
    ],
  },
  {
    id: "mns-creps",
    order: "02",
    title: "Vases Musee National du Sport et CREPS",
    mapLabel: "MNS / CREPS",
    chapter: "Serie signee, flamme olympique",
    shortDescription: "Deux vases issus du projet original de 2023 pour l'accueil de la flamme olympique dans les CREPS de France.",
    tone: "mns",
    physicalState: "Double rotation synchronisee",
    detailAction: "Premier clic: les deux vases s'animent ensemble. Dans le diaporama, chaque page declenche un tour complet; a la fin, une signature s'arrete pendant que le double tourne encore.",
    hardware: "Deux moteurs pas a pas Z couples",
    hotspot: { pxX: 1050, pxY: 550 },
    sketchImage: "main/png/mns-creps-croquis.png",
    gcodeHook: { name: "MNS CREPS double reveil synchronise", endpoint: "/api/choreo/run/mns_double_reveil" },
    slides: [
      {
        title: "Shooting 01",
        image: "diapo/vase-mns-creps/vase-mns-creps_01.JPG",
        caption: "La serie existe comme edition: trente pieces signees et numerotees.",
        sceneGcodeHook: { name: "MNS CREPS tour complet synchronise", endpoint: "/api/choreo/run/mns_tour_complet" },
      },
      {
        title: "Shooting 02",
        image: "diapo/vase-mns-creps/vase-mns-creps_02.JPG",
        caption: "L'artiste pose avec la serie, entre archive sportive et objet de ceremonie.",
        sceneGcodeHook: { name: "MNS CREPS tour complet shooting", endpoint: "/api/choreo/run/mns_tour_complet" },
      },
      {
        title: "Shooting 03",
        image: "diapo/vase-mns-creps/vase-mns-creps_03.JPG",
        caption: "Les rotations synchronisees donnent une lecture differente a chaque vase.",
        sceneGcodeHook: { name: "MNS CREPS axes differents", endpoint: "/api/choreo/run/mns_axes_differents" },
      },
      {
        title: "Shooting 04",
        image: "diapo/vase-mns-creps/vase-mns-creps_04.jpg",
        caption: "Un vase effectue un tour, l'autre repond par une pirouette.",
        sceneGcodeHook: { name: "MNS CREPS pirouette", endpoint: "/api/choreo/run/mns_pirouette" },
      },
      {
        title: "Shooting 05",
        image: "diapo/vase-mns-creps/vase-mns-creps_05.JPG",
        caption: "Le mouvement met en valeur la notion de revers, de numero et de signature.",
        sceneGcodeHook: { name: "MNS CREPS revers signature", endpoint: "/api/choreo/run/mns_signature" },
      },
      {
        title: "Shooting 06",
        image: "diapo/vase-mns-creps/vase-mns-creps_06.JPG",
        caption: "L'objet sportif devient un objet de transmission.",
        sceneGcodeHook: { name: "MNS CREPS tour complet transmission", endpoint: "/api/choreo/run/mns_tour_complet" },
      },
      {
        title: "Shooting 07",
        image: "diapo/vase-mns-creps/vase-mns-creps_07.JPG",
        caption: "Le rythme reste commun, mais les axes divergent.",
        sceneGcodeHook: { name: "MNS CREPS axes differents", endpoint: "/api/choreo/run/mns_axes_differents" },
      },
      {
        title: "Shooting 08",
        image: "diapo/vase-mns-creps/vase-mns-creps_08.JPG",
        caption: "Chaque changement de page relance une petite choregraphie.",
        sceneGcodeHook: { name: "MNS CREPS tour complet page", endpoint: "/api/choreo/run/mns_tour_complet" },
      },
      {
        title: "Shooting 09",
        image: "diapo/vase-mns-creps/vase-mns-creps_09.JPG",
        caption: "La serie se regarde autant comme collection que comme mouvement.",
        sceneGcodeHook: { name: "MNS CREPS tour complet serie", endpoint: "/api/choreo/run/mns_tour_complet" },
      },
      {
        title: "Signature",
        image: "diapo/vase-mns-creps/vase-mns-creps_10.JPG",
        caption: "La signature devient le point d'arret, pendant que l'autre vase continue de tourner.",
        sceneGcodeHook: { name: "MNS CREPS signature arretee double tourne", endpoint: "/api/choreo/run/mns_signature_finale" },
      },
    ],
  },
  {
    id: "asa",
    order: "03",
    title: "Vase ASA Blanc UV",
    mapLabel: "ASA",
    chapter: "Resistance, sable, vitrine",
    shortDescription: "Version blanche resistante aux rayons UV, presentee dans une vitrine avec sable et flux d'air module.",
    tone: "asa",
    physicalState: "Ventilateur puis agitation variable",
    detailAction: "Premier clic: le ventilateur met les grains de sable en mouvement. Deuxieme clic: le vase alterne gauche et droite avec des vitesses variables, comme s'il evitait les grains.",
    hardware: "Moteur pas a pas Y et ventilateur n.1",
    hotspot: { pxX: 792, pxY: 200},
    sketchImage: "main/png/asa-croquis.png",
    gcodeHook: { name: "ASA ventilateur sable", endpoint: "/api/choreo/run/asa_vent_sable" },
    slides: [
      {
        title: "Video ASA",
        video: "diapo/vase-asa/vase-asa.mp4",
        caption: "La sequence montre la resistance technique et le comportement de la matiere.",
        sceneGcodeHook: { name: "ASA debattement chaotique", endpoint: "/api/choreo/run/asa_debattement" },
      },
      {
        title: "Signature",
        video: "diapo/vase-asa/vase-asa-singature.mp4",
        caption: "Le vase devient un objet technique autant qu'un objet signe.",
        sceneGcodeHook: { name: "ASA alternance gauche droite", endpoint: "/api/choreo/run/asa_alternance" },
      },
    ],
  },
  {
    id: "podium",
    order: "04",
    title: "Vases Podium",
    mapLabel: "Podium",
    chapter: "Trois vases, buee et chance",
    shortDescription: "Trois vases en vitrine: une serie olympique pensee comme un dispositif de chance et d'apparition.",
    tone: "podium",
    physicalState: "Buee, chauffage, ventilation",
    detailAction: "Premier clic: le groupe pulse et un voile apparait. Deuxieme clic et parcours du diaporama: le plateau refroidit, le ventilateur expulse l'humidite, la buee disparait progressivement.",
    hardware: "Plateau chauffant, thermistance, ventilateur n.2",
    hotspot: { pxX: 927, pxY: 425 },
    sketchImage: "main/png/podium-croquis.png",
    gcodeHook: { name: "Podium voile de fumee", endpoint: "/api/choreo/run/podium_voile_fumee" },
    slides: [
      {
        title: "Video podium 01",
        video: "diapo/vase-podium/ektar-vase-podium-2.mp4",
        caption: "Les vases sont lies aux Jeux Olympiques, a la performance et aux gestes porte-bonheur.",
        sceneGcodeHook: { name: "Podium ventilation douce", endpoint: "/api/choreo/run/podium_ventilation_douce" },
      },
      {
        title: "Video podium 02",
        video: "diapo/vase-podium/teaser-vase-podium-1.mp4",
        caption: "La vitrine devient un petit theatre: chauffage, buee, ventilation et apparition progressive.",
        sceneGcodeHook: { name: "Podium buee disparition", endpoint: "/api/choreo/run/podium_buee_disparition" },
      },
    ],
  },
  {
    id: "poeme",
    order: "05",
    title: "Vase Poeme",
    mapLabel: "Poeme",
    chapter: "Alcove, timidite, face arriere",
    shortDescription: "Place dans une alcove, le vase se tourne lentement pour reveler le poeme inscrit sur sa face arriere.",
    tone: "poeme",
    physicalState: "Rotation lente et retenue",
    detailAction: "Premier clic: le vase se tourne presque timidement. Deuxieme clic: la lecture se poursuit avec une transcription et des vues de face et de revers.",
    hardware: "Moteur pas a pas E, corps chauffant et thermistance",
    hotspot: { pxX: 250, pxY: 210 },
    sketchImage: "main/png/poene-croquiss.png",
    gcodeHook: { name: "Poeme revelation timide", endpoint: "/api/choreo/run/poeme_revelation" },
    slides: [
      {
        title: "Face",
        image: "diapo/vase-poeme/vase-poeme-01.JPG",
        caption: "La face silencieuse prepare la revelation du texte.",
        sceneGcodeHook: { name: "Poeme face silencieuse", endpoint: "/api/choreo/run/poeme_face" },
      },
      {
        title: "Profil",
        image: "diapo/vase-poeme/vase-poeme-02.JPG",
        caption: "Le mouvement reste lent pour ne pas brusquer la lecture.",
        sceneGcodeHook: { name: "Poeme rotation retenue", endpoint: "/api/choreo/run/poeme_rotation_retenue" },
      },
      {
        title: "Revers",
        image: "diapo/vase-poeme/vase-poeme-03.jpg",
        caption: "Le poeme apparait comme une face cachee.",
        sceneGcodeHook: { name: "Poeme reveal face arriere", endpoint: "/api/choreo/run/poeme_reveal_arriere" },
      },
      {
        title: "Lecture",
        image: "diapo/vase-poeme/vase-poeme-04.JPG",
        caption: "La tablette rend lisible ce que le vase revele physiquement.",
        sceneGcodeHook: { name: "Poeme lecture arretee", endpoint: "/api/choreo/run/poeme_lecture_arret" },
      },
    ],
  },
];

window.REPLICATOR_CONSOLE_ORDER = ["poeme", "asa", "podium", "mns-creps"];

window.REPLICATOR_CHOREOGRAPHIES = [
  {
    id: "1",
    label: "Choregraphie 1",
    description: "Tous les vases tournent a la meme vitesse et les effets s'activent progressivement puis s'eteignent d'un seul coup.",
    gcodeHook: { name: "Global meme vitesse effets progressifs", endpoint: "/api/choreo/run/global_meme_vitesse" },
  },
  {
    id: "2",
    label: "Choregraphie 2",
    description: "Tous les vases accelerent progressivement tandis que les effets deviennent inactifs.",
    gcodeHook: { name: "Global acceleration effets off", endpoint: "/api/choreo/run/global_acceleration_effets_off" },
  },
  {
    id: "3",
    label: "Choregraphie 3",
    description: "Les vases partent en cascade du fond vers l'avant; chaque effet repond au vase precedent, puis tout revient au calme.",
    gcodeHook: { name: "Global cascade fond avant", endpoint: "/api/choreo/run/global_cascade_fond_avant" },
  },
  {
    id: "4",
    label: "Choregraphie 4",
    description: "Tous les vases ralentissent jusqu'a presque s'arreter; les effets restent suspendus, puis une extinction nette conclut la sequence.",
    gcodeHook: { name: "Global suspension extinction", endpoint: "/api/choreo/run/global_suspension_extinction" },
  },
];
